#!/bin/bash

# shellcheck disable=SC1091

set -o errexit
set -o nounset
set -o pipefail

[ -n "${DEBUG:+1}" ] && set -x

# Load libraries
. /opt/easysoft/scripts/liblog.sh
. /opt/easysoft/scripts/libmysql.sh
. /opt/easysoft/scripts/libfs.sh

# Load Global/Apache/PHP environment variables
. /etc/s6/s6-init/envs

#==================================#
# Prepare persistence directories. #
#==================================#
info "Prepare persistence directories."
for pdir in "${PHP_PERSISTENCE_LIST[@]}"
do
    # Ensure a directory exists and,is owned by the given user
    ensure_dir_exists "$pdir" "quickon"
done

# Make soft link for persistent directory
if [ ! -f /data/.init_cfg ];then
    for ldir in "${PERSISTENCE_LINK_LIST[@]}"
    do
        ensure_dir_exists "$(dirname $ldir)" "quickon"
        ensure_dir_exists "${ldir/data/apps}" "quickon" "777"
        mv "${ldir/data/apps}" "$(dirname $ldir)"
        make_soft_link "$ldir" "${ldir/data/apps}" "quickon"
    done

    info "For the first run, initialize the database."
    touch /data/db/database.sqlite && chown quickon.quickon /data/db/database.sqlite
    php artisan migrate:refresh
    php artisan passport:install
    echo "$APP_VERSION" > /data/.init_cfg
else
    for ldir in "${PERSISTENCE_LINK_LIST[@]}"
    do
        make_soft_link "$ldir" "${ldir/data/apps}" "quickon"
    done
fi

#=====================#
#   Prepare PHP       #
#=====================#
PHP_INI="/etc/php7/php.ini"
info "Render ${PHP_INI} with environment variables."
/usr/bin/render-template ${PHP_INI}.tpl > ${PHP_INI}

# Check and update db
INSTALL_VER=$(cat /data/.init_cfg)
if [ "$APP_VERSION" != "$INSTALL_VER" ];then
    warn "Install Version: $INSTALL_VER"
    warn "Image Version:APP_VERSION "
    warn "New version is detected,updating the database."
    php artisan migrate:refresh \
    && php artisan passport:install \
    && echo $APP_VERSION >/data/.init_cfg
fi

# init 2fauth
php artisan storage:link
php artisan config:cache